### ISSUE TITLE
zones not being picked up by node-red-contrib-node-homie-red v0.2.0

### ISSUE THREAD

**Issue by kskenyon** [ccutrer/waterfurnace_aurora#19]
For some reason the above node-red node picks up everything but the individual zones.  I have three and they show up OK in MQTT.  Could there be some formatting issue in the homie MQTT that prevents the zone info from showing up in the pull down in node-red property?

<img width="1728" alt="Screen Shot 2022-03-09 at 1 40 30 PM" src="https://user-images.githubusercontent.com/24734156/157509461-6e99da6d-93de-4be2-a1e7-da87c720cbfd.png">

**Comment by ccutrer** [comment]
I don't see any issues with the Homie metadata. OpenHAB's Homie implementation also reads everything correctly. Is there any Node-RED logging that might offer a clue?

**Comment by kskenyon** [comment]
Nothing in the Node-RED debug log.  The Property pull-down menu just doesn't populate for any of the zones.  Everything else seems to work as you can see.  I don't have OpenHAB or Homeassistant setup to check those.  I'll try that next.

**Comment by kskenyon** [comment]
Home Assistant seems to work OK.  Not sure what the problem in Node-Red is caused by.

**Comment by ccutrer** [comment]
Closing as it doesn't appear to be a problem with this gem.
