### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by rosenhauer** [ccutrer/waterfurnace_aurora#23]
I was getting no response in MQTT so I started researching and ran the "Start" commend manually so I could see the results. 

` sudo /usr/local/bin/aurora_mqtt_bridge /dev/ttyUSB0 mqtt://localhost/`

yields 

`/var/lib/gems/3.0.0/gems/rmodbus-ccutrer-2.1.0/lib/rmodbus/client/slave.rb:275:in 'rescue in query': Timed out during read attempt
`
I have confirmed that I am referencing the correct device ttyUSB0.  I also can see on a RS-485 Module on an ESP32 that is also connected to the buss that there is data sent  

`61 40 0C 61 61 61 58 76 54 61 7C 62 A8 40 64 02 61 A6 40 62 FF`  

That packet is sent twice before it gives the timeout error.  

I do have a different model USB to RS-485 Adapter than you show 
You list the DSD TECH SH-U11 USB to RS485 RS422 and I have the DSD TECH SH-U10 USB to RS485 Converter. Could that be the issue or do I have something else going on?

I have a Series 7 but am unsure of the Firmware version. 
Edit: I was able to send commands from the ESP32 and get that the ABC Program Version is 2.04 from register 2.

**Comment by BKFCAW** [comment]
Did you ever find a solution to this?  I recently bought an adapter with a CP2012 chip.  I believe I've wired it correctly, the driver appears to be installed (loaded with /etc/modules) on RPi 3B bullseye, /dev/ttyUSB0 is present, and the device shows up on lsusb, but when I try the test you described above, I get the same "timed out" error message.  Everything works when I use the adapter that is linked to Amazon in the original writeup.
