### ISSUE TITLE
QUESTION: which OS of raspberry pi are you imagining with that has the correct ruby version/environment to install the prerequisites

### ISSUE THREAD

**Issue by rabarar** [ccutrer/waterfurnace_aurora#28]
The version of Pi OS isn't installing the latest version of ruby - what's the stock image to use to successfully install the prerequisites and the repo?

**Comment by ccutrer** [comment]
You need to be on at least Raspberry Pi OS Bullseye.

**Comment by rabarar** [comment]
thx - that's what I figured... :) reimaged and it all installs as expected
