### ISSUE TITLE
Outstanding!

### ISSUE THREAD

**Issue by relevante** [ccutrer/waterfurnace_aurora#30]
My system isn't even fully installed yet and I have two instances of this running feeding into Home Assistant and it's absolutely amazing. Well-documented, well-executed, easy to get up and running, and so far rock solid. Seriously nice work. It's adding a huge amount of enjoyment to this system already. I've got template variables in HA to calculate real time COP, savings in terms of gallons, dollars, and pounds of carbon from the old oil system and so on. It's a bunch of fun squiggly lines and also just further reinforcing the feeling that I made the right choice with the system as a whole (incredibly it's outperforming the spec sheet by a pretty solid margin, which I wouldn't know without this library).

I'd expected to jump in and contribute something, but honestly it just feels complete at the moment. For a bit I had the thought of integrating some of the calculations for COP and such, but it kind of feels right that those calculations sit elsewhere and this is just a pure interface to the units themselves.

Thanks for the great work.

**Comment by ccutrer** [comment]
You're welcome! It always feels good knowing it's not just me using something I've put a lot of effort into, especially all the polishing into getting it past the "works for [just] me" stage.
