### ISSUE TITLE
MQTT Updates

### ISSUE THREAD

**Issue by starsoccer** [ccutrer/waterfurnace_aurora#44]
How often should data published via mqtt be updated, or is data only updated when an actual change takes place? Asking as I see some data that gets updated every few seconds, and then other points that seem to get 2 or 3 updates, and then never update again.

A good example of this is cooling set point. It gets updated when started, and then never updates again.

**Comment by ccutrer** [comment]
Any particular value is only published to MQTT when it changes (and at startup, to set the initial state). All messages are sent retained, so even if a subscriber wasn't around when it was originally sent, they'll still get the most recent value.

**Comment by starsoccer** [comment]
Well right after posting I was able to resolve this. For anyone else who hits this under the query options you can choose a fill option and select previous for it to just backfill the value
