### ISSUE TITLE
Split unit Extra information

### ISSUE THREAD

**Issue by starsoccer** [ccutrer/waterfurnace_aurora#52]
I recently had a split unit installed and while I currently have a serial device connected to the pump, I am curious if there is any other information I am missing by not having anything connected to the airhandler unit(assuming there is even a port)?

Is there any benefit to having a connection to it and the pump? Or is there any reason to be connected to one over the other(pump vs air handler)?

**Comment by heffneil** [comment]
I run both units and don't see any difference in the data.  The connection between the condenser and air handler is smart so all the data is available.
