### ISSUE TITLE
ABC Connection Cable Pin Description Error

### ISSUE THREAD

**Issue by jim0020** [ccutrer/waterfurnace_aurora#61]
In the section "Connecting to the ABC", it says "Connect pins 1 and 3 (white/orange and white/green for a TIA-568-B configured cable) to + and pins 2 and 4 (orange and green)"

In TIA-568B, pin 4 is blue, not green.  So either the pin numbers given are wrong, or the colors are wrong.

![](https://i.stack.imgur.com/EaOuY.png)

**Comment by 0n3man** [comment]
If you look at the table right below that text it has orange and blue as being connected.  If you also look at the picture of the actual cable he built, you'll see it's orange and blue which match the pins numbers 2 and 4.  I built my cable off the picture of the cable, and it worked fine.

**Comment by jim0020** [comment]
Thanks,  I found that section again with the picture.  There's a section below that that talks about using orange and green, which I kept finding first when scrolling up from the bottom and reading about the different commands.  I'm getting nothing over the connection, but I'm using a different RS485 to USB converter.  I ordered the one linked in the readme, which will be arriving tomorrow.
