### ISSUE TITLE
Cable Blows 3A Fuse Every Time I Connect

### ISSUE THREAD

**Issue by nyneaxis** [ccutrer/waterfurnace_aurora#67]
I have a brand new WF7 unit with AWL. As soon as I connect the cable into the AWL the unit shuts down. Checking the fuse, it is blown every time. I have followed the instructions and re-made the cable using the T568-B specs. I am also using the same USB adapter that is in the readme file. I have confirmed on both ends the pinouts. I taped the wires that are not being used to ensure they are not touching anything. I also made a brand new cable from a different cable. The adapter is not connected to anything when plugging in and is not touching anything. 

Thoughts?

**Comment by ccutrer** [comment]
That definitely sounds like a short. Do you have a multimeter to confirm voltage on each of the pins of your cable (before twisting any pairs together)?

**Comment by nyneaxis** [comment]
Thanks for replying. I tested today with a multimeter and found something strange. It wasn't the cable; I tested both ends for continuity and shorts. However, something made me check the board. I have the same one pictured. I used the link to Amazon from the repo. Pins 1 and 2 on the board are short. When using the multimeter and probing pins 1 and 2, I get continuity. I assume this shouldn't happen and is causing the short? Can you confirm that pins 1 and 2 on the board shouldn't show continuity?

**Comment by nyneaxis** [comment]
@ccutrer do you happen to know that correct ohm reading between the pins? I am getting 28 ohms across pins 1 and 2.

**Comment by djw1191** [comment]
@nyneaxis I assume you didn't resolve this? I just got a series 5 waterfurnace unit installed and inserted in doing this, just concerned about blowing the fuse (or causing some other issue). I assume the fuse is easy enough to replace if it blows?

**Comment by ccutrer** [comment]
Yes, it's quite easy to replace. Just a 3A automative fuse (the purple one). If you're genuinely worried, make sure you open the cabinet, are aware of where the fuse is, and have a couple on hand. They're _much_ cheaper online than if you have to go to a local auto parts store to get a pack for 3 or 5.

**Comment by djw1191** [comment]
Just in case someone encounters this issue in the future, similar to OP, I found that the linked USB -> serial adaptor only had around 15 ohms of resistance between A+ and B- which seemed close to a short to me and so I didn't end up trying it.

Ended up purchasing https://www.amazon.com/dp/B081MB6PN2 which had the more expected 120 ohms of resistance between pins and successfully worked.

**Comment by 0n3man** [comment]
> Just in case someone encounters this issue in the future, similar to OP, I found that the linked USB -> serial adaptor only had around 15 ohms of resistance between A+ and B- which seemed close to a short to me and so I didn't end up trying it.
> 
> Ended up purchasing https://www.amazon.com/dp/B081MB6PN2 which had the more expected 120 ohms of resistance between pins and successfully worked.

Did you get this alternative device to work?

**Comment by djw1191** [comment]
> Did you get this alternative device to work?

Yep, I bought two and both had no issues and are in use right now.

**Comment by 0n3man** [comment]
great, thanks for the update

**Comment by ccutrer** [comment]
I've updated the readme to also reference the alternative adapter. Weird - I've got 5 of the one I originally linked, purchased at varying times, and not had issues with any of them.
